const swaggerAutogen = require("swagger-autogen")({ openapi: "3.0.0" });

const doc = {
   info: {
      version: "2.0.0",
      title: "Helpoo Api Documentation",
      description:
         "Documentation automatically generated by the <b>swagger-autogen</b> module, for <b>Helpoo</b>.",
   },
   host: "apidev.helpooapp.net",
   basePath: "/",
   schemes: ["http", "https"],
   consumes: ["application/json"],
   produces: ["application/json"],
   tags: [
      {
         name: "User",
         description: "Endpoints",
      },
   ],
   securityDefinitions: {
      api_key: {
         type: "apiKey",
         name: "api_key",
         in: "header",
      },
   },
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./routes/index.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
   require("./app.js"); // Your project's root file
});
