module.exports = function ({ app }) {
   const accidentReports = require("./AccidentReportRoutes");
   const accidentTypesRoute = require("./accidentTypes");
   const branchRoutes = require("./BranchRoutes");
   const brokerRoutes = require("./brokerRoutes");
   const carModelRoute = require("./carModelRoute");
   const carRoute = require("./carRoutes");
   const carAccidentReport = require("./carAccidentReportRoutes");
   const clientRoute = require("./clientRoutes");
   const corporateRoute = require("./corporateRoutes");
   const countryRoutes = require("./CountryRoutes");
   const driverRoute = require("./driverRoutes");
   const fcmRoute = require("./fcmRoute");
   const historyLogsRoutes = require("./historyLogsRoutes");
   const insuranceCompanies = require("./InsuranceCompanyRoutes");
   const integrationRoutes = require("./IntegrationRouter");
   const inspectorsRoutes = require("./inspectorRoutes");
   const inspectionRoutes = require("./inspectionRoutes");
   const inspectionsCompanyRoutes = require("./InspectionCompanyRoutes");
   const manufacturersRoute = require("./manufacturerRoute");
   const packageRoutes = require("./packageRoutes");
   const paymobRouter = require("./paymobRouter");
   const packageCustomizationRoutes = require("./packageCustomization");
   const promoCodeRoute = require("./promoCodeRoute");
   const pdfTypeRoutes = require("./pdfTypeRoutes");
   const packagePromoRoutes = require("./PackagePromoRoute");
   const roleRoute = require("./roleRoutes");
   const ratingTypeServiceRoutes = require("./ratingTypeServiceRoutes");
   const smsRoute = require("./smsRoutes");
   const serviceRequestRouter = require("./serviceRequestRoutes");
   const settingsRoute = require("./SettingsRoutes");
   const serviceTypeRoutes = require("./serviceTypesRoutes");
   const trackingLogsRoutes = require("./trackingLogsRoutes");
   const vehicleRoute = require("./vehicleRoute");
   const userRoute = require("./userRoutes");

   app.use("/api/v2/accidentReports", accidentReports);
   app.use("/api/v2/accidentTypes", accidentTypesRoute);
   app.use("/api/v2/branches", branchRoutes);
   app.use("/api/v2/brokers", brokerRoutes);
   app.use("/api/v2/cars", carRoute);
   app.use("/api/v2/carAccidentReport", carAccidentReport);
   app.use("/api/v2/carModels", carModelRoute);
   app.use("/api/v2/corporates", corporateRoute);
   app.use("/api/v2/country", countryRoutes);
   app.use("/api/v2/clients", clientRoute);
   app.use("/api/v2/drivers", driverRoute);
   app.use("/api/v2/fcm", fcmRoute);
   app.use("/api/v2/history", historyLogsRoutes);
   app.use("/api/v2/inspections", inspectionRoutes);
   app.use("/api/v2/inspectionsCompany", inspectionsCompanyRoutes);
   app.use("/api/v2/inspect", inspectorsRoutes);
   app.use("/api/v2/insuranceCompanies", insuranceCompanies);
   app.use("/api/v2/manufacturers", manufacturersRoute);
   app.use("/api/v2/promoCode", promoCodeRoute);
   app.use("/api/v2/packages", packageRoutes);
   app.use("/api/v2/paymob", paymobRouter);
   app.use("/api/v2/packagesCustomization", packageCustomizationRoutes);
   app.use("/api/v2/packagePromo", packagePromoRoutes);
   app.use("/api/v2/pdfTypes", pdfTypeRoutes);
   app.use("/api/v2/roles", roleRoute);
   app.use("/api/v2/ratingTypeServices", ratingTypeServiceRoutes);
   app.use("/api/v2/settings", settingsRoute);
   app.use("/api/v2/sms", smsRoute);
   app.use("/api/v2/serviceRequest", serviceRequestRouter);
   app.use("/api/v2/typeSettings", serviceTypeRoutes);
   app.use("/api/v2/trackingLogs", trackingLogsRoutes);
   app.use("/api/v2/users", userRoute);
   app.use("/api/v2/vehicles", vehicleRoute);
   // * IntegrationRoutes
   app.use("/integration", integrationRoutes);
};
